/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_auxo_ame_lite_Mp3Encoder */

#ifndef _Included_io_auxo_ame_lite_Mp3Encoder
#define _Included_io_auxo_ame_lite_Mp3Encoder
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     io_auxo_ame_lite_Mp3Encoder
 * Method:    encode
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lio/auxo/ame/lite/Mp3Encoder$Options;Lio/auxo/ame/lite/Mp3Encoder$Callback;)V
 */
JNIEXPORT void JNICALL Java_io_auxo_ame_lite_Mp3Encoder_encode__Ljava_lang_String_2Ljava_lang_String_2Lio_auxo_ame_lite_Mp3Encoder_00024Options_2Lio_auxo_ame_lite_Mp3Encoder_00024Callback_2
  (JNIEnv *, jclass, jstring, jstring, jobject, jobject);

/*
 * Class:     io_auxo_ame_lite_Mp3Encoder
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_auxo_ame_lite_Mp3Encoder_getLameVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class io_auxo_ame_lite_Mp3Encoder_Options */

#ifndef _Included_io_auxo_ame_lite_Mp3Encoder_Options
#define _Included_io_auxo_ame_lite_Mp3Encoder_Options
#ifdef __cplusplus
extern "C" {
#endif
#undef io_auxo_ame_lite_Mp3Encoder_Options_STEREO
#define io_auxo_ame_lite_Mp3Encoder_Options_STEREO 0L
#undef io_auxo_ame_lite_Mp3Encoder_Options_JOINT_STEREO
#define io_auxo_ame_lite_Mp3Encoder_Options_JOINT_STEREO 1L
#undef io_auxo_ame_lite_Mp3Encoder_Options_DUAL_CHANNEL
#define io_auxo_ame_lite_Mp3Encoder_Options_DUAL_CHANNEL 2L
#undef io_auxo_ame_lite_Mp3Encoder_Options_MONO
#define io_auxo_ame_lite_Mp3Encoder_Options_MONO 3L
#undef io_auxo_ame_lite_Mp3Encoder_Options_NOT_SET
#define io_auxo_ame_lite_Mp3Encoder_Options_NOT_SET 4L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class io_auxo_ame_lite_Mp3Encoder_Options_MPEGMode */

#ifndef _Included_io_auxo_ame_lite_Mp3Encoder_Options_MPEGMode
#define _Included_io_auxo_ame_lite_Mp3Encoder_Options_MPEGMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class io_auxo_ame_lite_Mp3Encoder_Callback */

#ifndef _Included_io_auxo_ame_lite_Mp3Encoder_Callback
#define _Included_io_auxo_ame_lite_Mp3Encoder_Callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
