/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_auxo_ame_Mp3Encoder */

#ifndef _Included_io_auxo_ame_Mp3Encoder
#define _Included_io_auxo_ame_Mp3Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_auxo_ame_Mp3Encoder
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_auxo_ame_Mp3Encoder_getLameVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
